name: Deploy to Caddy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [content-updated]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout astro repository
        uses: actions/checkout@v4
        with:
          path: portfolio-astro

      - name: Checkout content repository
        uses: actions/checkout@v4
        with:
          repository: komoriyuta/portfolio-content
          path: portfolio-content
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: portfolio-astro/package-lock.json

      - name: Install dependencies
        working-directory: portfolio-astro
        run: npm ci

      - name: Build Astro
        working-directory: portfolio-astro
        run: npm run build

      - name: Deploy to Caddy Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "portfolio-astro/dist/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
